# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - SpringBoot-PG-Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      
      - name: Download Gradle Wrapper
        run: |
          curl -LO "https://services.gradle.org/distributions/gradle-7.6.1-bin.zip"
          unzip -q gradle-7.6.1-bin.zip
          rm gradle-7.6.1-bin.zip

      - name: Build with Gradle
        run: ./gradle-7.6.1/bin/gradle clean build -x test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: build
          
      - name: List files in deployment directory
        run: ls build/libs/
      
      - name: Set up PostgreSQL environment variables
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> $GITHUB_ENV
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> $GITHUB_ENV
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT }}/${{ secrets.DATABASE_NAME }}?user=${{ secrets.DATABASE_USERNAME }}&password=${{ secrets.DATABASE_PASSWORD }}&sslmode=require" >> $GITHUB_ENV
          echo "SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect" >> $GITHUB_ENV

 #    - name: Deploy to Azure Web App
 #       id: deploy-to-webapp
 #       uses: azure/webapps-deploy@v2
 #       with:
 #         app-name: 'SpringBoot-PG-Azure'
 #         slot-name: 'Production'
 #        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D0E4A5891D3E49EFB68866CF93F44E67 }}
 #         package: build/libs/SpringGradleapi-0.0.1-SNAPSHOT-plain.jar


env:
  spring_profiles_active: master_springboot-pg-azure
  spring_datasource_url: jdbc:postgresql://localhost:5432/employee:5432;database=employee;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  spring_datasource_username: ${{ secrets.DATABASE_USERNAME }}
  spring_datasource_password: ${{ secrets.DATABASE_PASSWORD }}
  spring_jpa_show-sql: true
  spring_jpa_hibernate_ddl-auto: update
  spring_jpa_hibernate_dialect: org.hibernate.dialect.PostgreSQLDialect
  server_port: 9191